version: '3'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 library_hack.wsgi:application
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3  # Монтируем файл базы данных SQLite
    expose:
      - 8000

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - web  # Nginx должен дождаться, пока запустится web
