# Generated by Django 5.1.1 on 2024-09-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0002_userlikedcategories_customuser_fcs_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlikedcategories",
            name="user",
            field=models.ManyToManyField(to="cores.userprofile"),
        ),
    ]
