# Generated by Django 5.1.1 on 2024-09-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0003_userlikedcategories_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userlikedcategories",
            name="user",
        ),
        migrations.AddField(
            model_name="userlikedcategories",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_categories",
                to="cores.userprofile",
            ),
            preserve_default=False,
        ),
    ]
