# Generated by Django 5.1.1 on 2024-09-06 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cores", "0004_remove_userlikedcategories_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlikedcategories",
            options={
                "verbose_name": "User Liked Category",
                "verbose_name_plural": "User Liked Categories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="userlikedcategories",
            unique_together={("user", "category")},
        ),
    ]
