# Generated by Django 5.1.1 on 2024-09-06 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0006_userfavoritebook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fcs',
            new_name='full_name',
        ),
    ]
