# Generated by Django 5.1.1 on 2024-09-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cores', '0007_rename_fcs_customuser_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
